Hw04 auth
Vittalina/nodejs-rest-api pull request #3
Opened 2022-11-13 20:12 UTC by Vittalina

2022-11-14 14:27 UTC, Eastvarga commented on controllers/auth.controller.js
> +  return res.status(201).json({
Не відповідає ТЗ. Не критично як для навчання, але те що багато елементів не відповідає ТЗ, важко перевіряти роботи. Будь ласка приведіть все до відповідності ТЗ.

2022-11-14 14:30 UTC, Eastvarga commented on controllers/auth.controller.js
> +    expiresIn: "15m",
Ви перевіряли чи працює Ваш код як треба? Краще використовуйте конфіг файл в якому будуть усі конфігураційні сталі/змінні середовища. замість  expiresIn: "15m", спробуйте expiresIn: 3600 числове представлення часу у секундах

2022-11-14 14:32 UTC, Eastvarga commented on controllers/auth.controller.js
> +  await User.findByIdAndUpdate(user._id, user);
findByIdAndUpdate наче дає можливість вказувати лише ті поля що треба змінити без необхідності використовувати усього юзера

2022-11-14 14:34 UTC, Eastvarga commented on controllers/auth.controller.js
> +  return res.status(200).json({ status: "success", Userdata });
Ви впевнені що повертаеться саме такий об'єкт  {
  "email": "example@example.com",
  "subscription": "starter"
} у відповіді?

2022-11-14 15:18 UTC, Eastvarga commented on controllers/contacts.controllers.js
> +    favourite,
Чи перевіряли ви роботу свого коду?
 { favorite }, ось запис для оновлення поля контакту.

2022-11-14 15:24 UTC, Eastvarga commented on controllers/user.controller.js
> +const { User: UserModel } = require("../models/user.model");
Навіщо цей файл, та що він повинен робити?

2022-11-14 15:24 UTC, Eastvarga commented on middlewares/auth.js
> +  console.log("auth middleware", req.headers.authorization);
Ніяких логів у робочому коді не повинно бути

2022-11-14 15:25 UTC, Eastvarga commented on middlewares/auth.js
> +        next(new Unauthorized("token is invalid"));
Де перевірка чи юзер вилогінився? де перевірка токена який у юзері. Чому вилогінений юзер може мати доступ до раута?

2022-11-14 15:28 UTC, Eastvarga commented on routes/contacts.router.js
>  contactsRouter.patch(
Чи коректно  вказаний шлях відповідно до ТЗ?

2022-11-14 15:28 UTC, Eastvarga commented on routes/user.router.js
> +  tryCatchWrapper(userController.getContacts)
Що це та навіщо?

2022-11-14 15:30 UTC, Eastvarga requested changes
Є зауваження. Треба усунути невідповідності ТЗ, та перевіряти процездатність коду.

2022-11-15 10:31 UTC, Vittalina commented on controllers/auth.controller.js
> +    expiresIn: "15m",
Підкажіть, будь ласка, де це знайти в документації?

2022-11-15 12:00 UTC, Eastvarga commented on controllers/auth.controller.js
> +    expiresIn: "15m",
Зазвичай у доках пакетів є інформація, але я завжди також дивлюсь у самому коді, де той або інший код імплементован.

2022-11-15 17:55 UTC, Eastvarga commented on controllers/contacts.controllers.js
> +    res.status(400).json({ message: "Not found" });
Чому виправили на 400? Це невідповідність текста коду чи кода тексту?

2022-11-15 17:58 UTC, Eastvarga commented on controllers/user.controller.js
> +  user.token = token;
Здається це зайва строка коду яка нічого не робить

2022-11-15 18:02 UTC, Eastvarga commented on controllers/user.controller.js
> +  await User.findByIdAndUpdate(user._id, user);
await User.findByIdAndUpdate(user._id, { token:null }); а такий запис не буде кращим? Тоді не треба 
  user.token = null;
на логауті у Вас мідлвар аутентифікації, якщо він не кинув помилку, отже код перейшов до функції логауту яка повинна просто обнулити токен у юзера. Тобто просто апдейтити поле токена

2022-11-15 18:09 UTC, Eastvarga commented on middlewares/auth.js
> +        next(new Unauthorized("token is invalid"));
Що буде якщо юзер залогіниться =>збереже токен => проведе логаут => знову залогіниться=> використає для доступу до раута попередньо збережений токен першого логіна? Чому  таке допускає Ваша реалізація логіна?

2022-11-15 18:10 UTC, Eastvarga requested changes
Є декілька зауважень, бажано їх усунути

2022-11-16 10:41 UTC, Vittalina commented on controllers/user.controller.js
> +  user.token = token;
Маєте на увазі user.token = token? Саме цю функцію робила точнісінько як в лектора. То вона зайва? Я так зрозуміла, expiresIn: "1h" взагалі можна прибрати, це ж додаткова опція.

2022-11-16 19:29 UTC, Eastvarga commented on controllers/user.controller.js
> +  user.token = token;
У Вашому випадку так

2022-11-16 19:40 UTC, Eastvarga commented on middlewares/auth.js
> +    const [, token] = authHeader.split(" ");
Чому не перевіряєте формат авторизації запиту, "Bearer token"? Гадаєте вона не потрібна, чи Вам того не показували?

2022-11-16 19:42 UTC, Eastvarga commented on middlewares/auth.js
> +    const user = jwt.decode(token, JWT_SECRET);
Оце дуже цікавий метод він декодує заряд токену, але як Ви верифікуєте користувача?

2022-11-16 19:43 UTC, Eastvarga commented on middlewares/auth.js
> +
user.token=token
req.user= user
і Все, навіщотокен до запиту додаєте ще

2022-11-16 19:44 UTC, Eastvarga requested changes
Є зауваження до роботи авторизації, бажано їх усунути

2022-11-17 15:39 UTC, Eastvarga approved these changes

2022-11-17 16:31 UTC, Eastvarga approved these changes

2022-11-17 16:47 UTC, merged